version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 10
    target-branch: test
    ignore:
      - dependency-name: cheerio
        versions:
          - '> 1.0.0-rc.3'
      - dependency-name: aws-sdk
        versions:
          - 2.838.0
          - 2.839.0
          - 2.842.0
          - 2.847.0
          - 2.852.0
          - 2.857.0
          - 2.862.0
          - 2.867.0
          - 2.868.0
          - 2.873.0
          - 2.876.0
          - 2.878.0
          - 2.883.0
          - 2.889.0
          - 2.890.0
      - dependency-name: npm
        versions:
          - 6.14.11
          - 7.10.0
          - 7.5.2
          - 7.5.3
          - 7.5.4
          - 7.5.6
          - 7.6.0
          - 7.6.1
          - 7.6.2
          - 7.6.3
          - 7.7.5
          - 7.7.6
          - 7.8.0
          - 7.9.0
      - dependency-name: '@angular/cli'
        versions:
          - 11.1.2
          - 11.1.3
          - 11.2.0
          - 11.2.1
          - 11.2.2
          - 11.2.3
          - 11.2.4
          - 11.2.5
          - 11.2.6
          - 11.2.8
          - 11.2.9
      - dependency-name: '@testing-library/user-event'
        versions:
          - 12.8.1
          - 12.8.3
          - 13.0.16
          - 13.0.2
          - 13.0.7
          - 13.0.8
          - 13.1.1
          - 13.1.2
      - dependency-name: '@types/faker'
        versions:
          - 5.5.0
          - 5.5.1
      - dependency-name: '@sentry/browser'
        versions:
          - 6.1.0
          - 6.2.0
          - 6.2.2
          - 6.2.5
      - dependency-name: '@angular/language-service'
        versions:
          - 11.1.1
          - 11.1.2
          - 11.2.1
          - 11.2.2
          - 11.2.3
          - 11.2.4
          - 11.2.5
          - 11.2.6
          - 11.2.7
          - 11.2.8
          - 11.2.9
      - dependency-name: core-js
        versions:
          - 3.10.0
          - 3.10.1
          - 3.8.3
          - 3.9.1
      - dependency-name: ua-parser-js
        versions:
          - 0.7.25
          - 0.7.26
          - 0.7.27
      - dependency-name: '@testing-library/angular'
        versions:
          - 10.4.1
          - 10.4.2
          - 10.5.0
      - dependency-name: faker
        versions:
          - 5.5.0
          - 5.5.2
      - dependency-name: eslint-config-prettier
        versions:
          - 8.1.0
      - dependency-name: js-yaml
        versions:
          - 4.0.0
      - dependency-name: '@angular-eslint/eslint-plugin-template'
        versions:
          - 2.0.2
      - dependency-name: '@testing-library/dom'
        versions:
          - 7.30.1
      - dependency-name: '@angular-devkit/build-angular'
        versions:
          - 0.1102.6
      - dependency-name: typescript
        versions:
          - 4.0.7
          - 4.2.3
      - dependency-name: '@angular-eslint/eslint-plugin'
        versions:
          - 2.0.2
      - dependency-name: karma
        versions:
          - 6.2.0
          - 6.3.1
      - dependency-name: '@angular-eslint/builder'
        versions:
          - 2.0.2
      - dependency-name: sinon
        versions:
          - 10.0.0
      - dependency-name: '@angular-eslint/schematics'
        versions:
          - 2.0.2
      - dependency-name: '@angular-eslint/template-parser'
        versions:
          - 2.0.2
      - dependency-name: '@angular/animations'
        versions:
          - 11.2.7
      - dependency-name: '@angular/core'
        versions:
          - 11.2.7
      - dependency-name: '@types/node'
        versions:
          - 14.14.33
          - 14.14.36
      - dependency-name: '@angular/cdk'
        versions:
          - 11.2.6
      - dependency-name: '@types/jasmine'
        versions:
          - 3.6.6
          - 3.6.7
          - 3.6.8
      - dependency-name: husky
        versions:
          - 5.0.9
          - 5.1.1
          - 5.1.3
          - 5.2.0
      - dependency-name: '@sentry/node'
        versions:
          - 6.1.0
          - 6.2.0
          - 6.2.1
          - 6.2.2
          - 6.2.3
      - dependency-name: '@sentry/tracing'
        versions:
          - 6.1.0
          - 6.2.0
          - 6.2.1
          - 6.2.2
          - 6.2.3
      - dependency-name: eslint
        versions:
          - 7.21.0
          - 7.22.0
      - dependency-name: chai
        versions:
          - 4.3.3
          - 4.3.4
      - dependency-name: rxjs
        versions:
          - 6.6.6
      - dependency-name: rxjs-compat
        versions:
          - 6.6.6
      - dependency-name: mocha
        versions:
          - 8.3.2
      - dependency-name: exceljs
        versions:
          - 4.2.1
      - dependency-name: jspdf
        versions:
          - 2.3.0
          - 2.3.1
      - dependency-name: convict
        versions:
          - 6.0.1
      - dependency-name: convict-format-with-validator
        versions:
          - 6.0.1
      - dependency-name: sqreen
        versions:
          - 1.62.0
      - dependency-name: slugify
        versions:
          - 1.4.7
      - dependency-name: pug
        versions:
          - 3.0.2
      - dependency-name: url-parse
        versions:
          - 1.5.1
      - dependency-name: highcharts-angular
        versions:
          - 2.10.0
          - 2.9.0
      - dependency-name: helmet
        versions:
          - 4.4.1
      - dependency-name: puppeteer
        versions:
          - 5.5.0
      - dependency-name: highcharts
        versions:
          - 9.0.0
