#This is the test credentials for test purpose only and not introduced in the main branch
contrast: 
  url: https://eval.contrastsecurity.com/Contrast
  api_key: xfFhonYE0172F7AozbdA98a5TIaGEIMd
  service_key: BENBZKG2ILDVRZ82
  user_name: agent_383500ab-6ac3-4f2f-a654-446c17128276@SopraSteria
