version: 0.2

phases:
  build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - cd frontend/src
      - aws s3 cp --recursive . s3://sfc-frontend-build-artifacts/$COMMIT_HASH
