module.exports.Permissions = {
  uid: '4698f4a4-ab82-4906-8b0e-3f4972375927',
  permissions: {
    canAddUser: true,
    canAddEstablishment: true,
    canAddWorker: true,
    canBulkUpload: true,
    canChangePermissionsForSubsidiary: true,
    canChangeDataOwner: true,
    canDeleteEstablishment: true,
    canDeleteUser: true,
    canDeleteWorker: true,
    canEditUser: true,
    canEditWorker: true,
    canViewEstablishment: true,
    canViewWdfReport: true,
    canViewWorker: true,
    canCountWorkers: true,
    canViewVisuals: true,
    canViewLastUpdateTime: true,
    canViewNotifications: true,
    canSortEstablishments: true,
    canSortWorkers: true,
    canTransferWorker: true,
    canViewListOfWorkers: true,
    canEditEstablishment: true,
    canViewUser: true,
    canViewListOfUsers: true,
    canRunLocalAuthorityReport: true,
  },
};

module.exports.PermissionsList = {
  '4698f4a4-ab82-4906-8b0e-3f4972375927': true,
};
