exports.mockWorkerTrainingBreakdowns = [
  {
    name: 'Bob Test',
    trainingCount: 6,
    qualificationCount: 2,
    expiredTrainingCount: 2,
    expiredMandatoryTrainingCount: 0,
    expiredNonMandatoryTrainingCount: 2,
    expiringTrainingCount: 4,
    expiringMandatoryTrainingCount: 2,
    expiringNonMandatoryTrainingCount: 2,
    missingMandatoryTrainingCount: 0,
    mandatoryTrainingCount: 0,
  },
  {
    name: 'Mike test',
    trainingCount: 10,
    qualificationCount: 0,
    expiredTrainingCount: 6,
    expiredMandatoryTrainingCount: 3,
    expiredNonMandatoryTrainingCount: 3,
    expiringTrainingCount: 0,
    expiringMandatoryTrainingCount: 0,
    expiringNonMandatoryTrainingCount: 0,
    missingMandatoryTrainingCount: 0,
    mandatoryTrainingCount: 5,
  },
  {
    name: 'Andrew Test',
    trainingCount: 13,
    qualificationCount: 0,
    expiredTrainingCount: 0,
    expiredMandatoryTrainingCount: 0,
    expiredNonMandatoryTrainingCount: 0,
    expiringTrainingCount: 2,
    expiringMandatoryTrainingCount: 0,
    expiringNonMandatoryTrainingCount: 2,
    missingMandatoryTrainingCount: 2,
    mandatoryTrainingCount: 3,
  },
  {
    name: 'Daniel Craig',
    trainingCount: 6,
    qualificationCount: 0,
    expiredTrainingCount: 4,
    expiredMandatoryTrainingCount: 1,
    expiredNonMandatoryTrainingCount: 3,
    expiringTrainingCount: 2,
    expiringMandatoryTrainingCount: 0,
    expiringNonMandatoryTrainingCount: 2,
    missingMandatoryTrainingCount: 3,
    mandatoryTrainingCount: 3,
  },
];

exports.mockWorkerQualificationRecords = [
  {
    workerName: 'Helen Jones',
    jobRole: 'Administrative / office staff not care-providing',
    qualificationType: 'Degree',
    qualificationName: 'Health and Social Care degree',
    qualificationLevel: '6',
    yearAchieved: 2020,
  },
  {
    workerName: 'Anna Riley',
    jobRole: 'Care Worker',
    qualificationType: 'Apprenticeship',
    qualificationName: 'Adult Care Worker (standard)',
    qualificationLevel: '3',
    yearAchieved: 2010,
  },
  {
    workerName: 'Bob Smith',
    jobRole: 'Activities worker or co-ordinator',
    qualificationType: 'NVQ',
    qualificationName: 'Care NVQ',
    qualificationLevel: null,
    yearAchieved: null,
  },
];
