aws:
    region: eu-west-1
    secrets:
        use: true
        wallet: benchmarks/api
    sns:
      enabled: true
      registrations: arn:aws:sns:eu-west-1:364648107127:registrations-dev
      feedback: 	arn:aws:sns:eu-west-1:364648107127:feedback-dev

db:
    pool:
        min: 10
        max: 10
    ssl: true

slack:
    level : 3     # enables Slack notifications

jwt:
    iss: 'sfcbenchmarks.cloudapps.digital'
    ttl:
        login: 30

bulkupload:
    region: eu-west-2
    bucketname: sfc-bulkupload-dev
    validation:
        timeout: 300
        storeIntermediaries: true
    completion:
        timeout: 180

locks:
    region: eu-west-1
    bucketname: sfc-locks-dev

# no notify definition - not used in development
