aws:
    region: eu-west-1
    secrets:
        use: false
        wallet: dev/api
    kinesis:
      enabled: true
      establishments: establishments.dev
      workers: workers.dev
      users: users.dev
    sns:
      enabled: true
      registrations: arn:aws:sns:eu-west-1:364648107127:registrations-dev
      feedback: 	arn:aws:sns:eu-west-1:364648107127:feedback-dev

log:
    sequelize: true

db:
    pool:
        min: 15
        max: 15
    ssl: true
    username: aaron_russell
    host: '35.178.185.248'
    password: 'xs32MtxJXuhndCkBtxOy3Yp9FDqtHnW5tlhjsdcHSYGzVkMaOmFDiaJdBG8LC9pO2QaKnG'
    client_ssl:
        status: true
        usingFiles: true
        files:
          certificate: /mnt/c/Users/arussell/Documents/Repos/SFC-Certs/pg_dev_client.crt
          key: /mnt/c/Users/arussell/Documents/Repos/SFC-Certs/pg_dev_client.key
          ca: /mnt/c/Users/arussell/Documents/Repos/SFC-Certs/pg_dev_root.crt

slack:
    level : 3     # enables Slack notifications

jwt:
    iss: 'sfcdev.cloudapps.digital'
    ttl:
        login: 30

bulkupload:
    region: eu-west-2
    bucketname: sfc-bulkupload-dev
    validation:
        timeout: 300
        storeIntermediaries: true
    completion:
        timeout: 180

public:
    download:
        baseurl: https://sfc-public-dev.s3.eu-west-2.amazonaws.com/public/download

# no notify definition - not used in development
