aws:
    region: eu-west-1
    secrets:
        use: true
        wallet: dev/api

db:
    pool: 5
    ssl: true
    username: sfcapp
    client_ssl:
        status: true
        usingFiles: false

slack:
    level : 3     # enables Slack notifications

jwt:
    iss: 'sfcdev.cloudapps.digital'
    ttl:
        login: 30

bulkupload:
    region: eu-west-2
    bucketname: sfc-bulkupload-dev

# no notify definition - not used in development