aws:
  region: eu-west-1
  secrets:
    use: true
    wallet: preprod/api
  sns:
    enabled: true
    registrations: arn:aws:sns:eu-west-1:364648107127:registrations-preprod
    feedback: arn:aws:sns:eu-west-1:364648107127:feedback-preprod

slack:
  level: 3 # enables Slack notifications

jwt:
  iss: 'asc-wds.skillsforcare.org.uk'
  ttl:
    login: 30

db:
  pool:
    min: 100
    max: 300
    acquire: 240000
    idle: 200000
  ssl: true
  client_ssl:
    status: false
    usingFiles: false

notify:
  replyTo: '73711295-a4da-4303-9127-65be2a409681'
  templates:
    resetPassword: 'f2c43610-9ec9-4271-b9b1-dd55569b191c'
    addUser: 'e581eea2-4206-4c90-8594-4357960e3e74'

bulkupload:
  region: eu-west-2
  bucketname: sfc-bulkupload-preprod
  validation:
    timeout: 300
    storeIntermediaries: false
  completion:
    timeout: 120

locks:
  region: eu-west-1
  bucketname: sfc-locks-preprod

public:
  download:
    baseurl: https://sfc-public-prod.s3.eu-west-2.amazonaws.com/public/download
