version: '3'
services:
  sfc-test:
    image: postgres:13
    container_name: sfc-test
    build:
      context: .
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 90:5432
