aws:
  region: eu-west-1
  secrets:
    use: true
    wallet: dev/api
  sns:
    enabled: true
    registrations: arn:aws:sns:eu-west-1:364648107127:registrations-dev
    feedback: arn:aws:sns:eu-west-1:364648107127:feedback-dev

db:
  pool:
    min: 15
    max: 15
  ssl: true
  username: sfcapp

slack:
  level: 3 # enables Slack notifications

jwt:
  iss: 'sfcdev.cloudapps.digital'
  ttl:
    login: 30

bulkupload:
  region: eu-west-2
  bucketname: sfc-bulkupload-dev
  validation:
    timeout: 300
  completion:
    timeout: 180

disbursement:
  region: eu-west-2
  bucketname: wdf-disbursement-dev

locks:
  region: eu-west-1
  bucketname: sfc-locks-dev

public:
  download:
    baseurl: https://sfc-public-dev.s3.eu-west-2.amazonaws.com/public/download
# no notify definition - not used in development
