AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sendingEmails


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3


Resources:
  SendEmailsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sendEmails/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SendEmailsQueueSQS.Arn
            BatchSize: 1
            Enabled: true

  SendEmailsQueueSQS:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      KmsMasterKeyId: alias/aws/sqs


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SendEmailsFunction:
    Description: "Send Emails Lambda Function ARN"
    Value: !GetAtt SendEmailsFunction.Arn
  SendEmailsFunctionIamRole:
    Description: "Implicit IAM Role created for Send Emails function"
    Value: !GetAtt SendEmailsFunctionRole.Arn
  SendEmailsQueueSQS:
    Description: "Send Emails SQS Queue ARN"
    Value: !GetAtt SendEmailsQueueSQS.Arn

