// http://localhost:3000/api/test/locations/random?limit=5
exports.data = [
  {
    address1: 'Peppermill Court',
    address2: 'Ramsay Close',
    townAndCity: 'York',
    county: 'North Yorkshire',
    postcode: 'YO31 8SS',
    mainServiceName: 'Hospitals - Mental health/capacity',
    locatioName: 'Peppermill Court',
    locationId: 'RX34L',
  },
  {
    address1: 'Navigation Park',
    address2: 'Waters Meeting Road',
    townAndCity: 'Bolton',
    county: 'Lancashire',
    postcode: 'BL1 8TT',
    mainServiceName: 'Doctors/Gps',
    locatioName: 'Burnside Surgery',
    locationId: '1-558964369',
  },
  {
    address1: 'Derbyshire House',
    address2: 'Station Road, East Leake',
    townAndCity: 'Loughborough',
    county: 'Leicestershire',
    postcode: 'LE12 6LQ',
    mainServiceName: 'Residential homes',
    locatioName: 'Derbyshire House Residential Care',
    locationId: '1-3580606655',
  },
  {
    address1: '157 Broadway',
    address2: null,
    townAndCity: 'Peterborough',
    county: 'Cambridgeshire',
    postcode: 'PE1 4DD',
    mainServiceName: 'Dentist',
    locatioName: 'Peterborough Onefiveseven Partnership',
    locationId: '1-2319144453',
  },
  {
    address1: '41 Dodmore Lane',
    address2: null,
    townAndCity: 'Ludlow',
    county: 'Shropshire',
    postcode: 'SY8 2NN',
    mainServiceName: 'Homecare agencies',
    locatioName: 'Quality community care ltd',
    locationId: '1-2873735573',
  },
];
