export const removePersonalInformationForWorker = Object.freeze({
  NameOrIdValue: '',
  NationalInsuranceNumberValue: null,
  DateOfBirthValue: null,
  PostcodeValue: null,
  DisabilityValue: null,
  GenderValue: null,
  EthnicityFkValue: null,
  EthnicityFKValue: null,
  NationalityValue: null,
  NationalityOtherFK: null,
  CountryOfBirthValue: null,
  CountryOfBirthOtherFK: null,
  RecruitedFromValue: null,
  RecruitedFromOtherFK: null,
  BritishCitizenshipValue: null,
  YearArrivedValue: null,
  YearArrivedYear: null,
  DateOfBirthEncryptedValue: null,
  NationalInsuranceNumberEncryptedValue: null,
  HealthAndCareVisaValue: null,
});
