exports.registrationWithUser = {
  NameValue: 'Care Home 1',
  IsRegulated: false,
  LocationID: null,
  ProvID: null,
  Address1: 'Unit 1A, Sunset House',
  Address2: 'Sunset Lane',
  Address3: null,
  Town: 'Leeds',
  County: 'Yorkshire',
  PostCode: 'LS1 1AA',
  NmdsID: 'I1003080',
  EstablishmentID: 1010,
  ParentID: null,
  ParentUID: null,
  created: '2021-11-08T17:01:34.931Z',
  updatedBy: 'username',
  Status: 'PENDING',
  EstablishmentUID: 'bbd7d85c-3550-438b-a0fc-d83a96c6a6bb',
  Reviewer: null,
  InReview: false,
  EmployerTypeValue: 'Private Sector',
  EmployerTypeOtherValue: null,
  mainService: { id: 15, name: 'Any other services' },
  users: [
    {
      EmailValue: 'jenny@email.com',
      PhoneValue: '01234567890',
      FullNameValue: 'Jenny Jones',
      SecurityQuestionValue: 'some question',
      SecurityQuestionAnswerValue: 'some answer',
      created: '2021-11-08T17:01:34.931Z',
      login: {
        id: 1909,
        username: 'username',
        get: (field) => this.registrationWithUser.users[0].login[field.toString()],
      },
      get: (field) => this.registrationWithUser.users[0][field.toString()],
    },
  ],
  get: (field) => this.registrationWithUser[field.toString()],
};

exports.convertedRegistrationResponse = {
  created: '8/11/2021 5:01pm',
  username: 'username',
  establishment: {
    id: 1010,
    name: 'Care Home 1',
    isRegulated: false,
    nmdsId: 'I1003080',
    address: 'Unit 1A, Sunset House',
    address2: 'Sunset Lane',
    address3: null,
    postcode: 'LS1 1AA',
    town: 'Leeds',
    county: 'Yorkshire',
    locationId: null,
    provid: null,
    mainService: 'Any other services',
    parentId: null,
    parentUid: null,
    parentEstablishmentId: null,
    status: 'PENDING',
    uid: 'bbd7d85c-3550-438b-a0fc-d83a96c6a6bb',
    reviewer: null,
    inReview: false,
    employerType: {
      value: 'Private Sector',
      other: null,
    },
  },
  name: 'Jenny Jones',
  securityQuestion: 'some question',
  securityQuestionAnswer: 'some answer',
  email: 'jenny@email.com',
  phone: '01234567890',
};
